### ISSUE TITLE
pcapng-file isn't limited when it is returned for REST-request: /logging/kismetdb/pcap/packets

### ISSUE THREAD

**Issue by pahanco** [kismetwireless/kismet#335] opened 2021-01-06 13:40 UTC
REST-request: "/devices/pcap/by-key/..." is designated to return stream of pcap's pieces, which are stored to a file while downloading. In fact, there isn't limit in filesize or packets number in the file. So, if I request file by such REST, I will be getting data and this data will stop never. So, browser doesn't create result file, which I can take and save. It downloads stream to temporary file all the time.

But ctor `pcapng_stream_packetchain::pcapng_stream_packetchain()` has `max_backlog` parameter, which is used for limit filesize. Class `pcapng_stream_packetchain` is inherited from `pcapng_stream_futurebuf` and that one is inherited from `streaming_agent`, which has member `max_size`. I found out that `streaming_agent::max_size` is zero all the time, so object of  `streaming_agent`doesn't check limit size of data. 

I try to call `streaming_agent::set_max_size( max_backlog )` in pcapng_stream_futurebuf::pcapng_stream_futurebuf()`. It seems as work solution.

**Comment by kismetwireless** [comment] 2021-01-06 14:55
This is actually by design, the pcapng endpoint is designed to provide a constant stream of live data; cancelling it is the responsibility of the calling tool.  Typically this would be used for mirroring packets over a continual http stream, piping them into tcpdump or tshark, etc.  Whatever you call it with should be handling cancelling the connection after it gets however many packets it wants, or whatever time period it's connected for.

With most scripting languages you should be able to fairly easily set a total request time, or have a mechanism for handling it - for instance the eventlet library which can set timeouts on other actions in python, i'm sure the equivalent exists on other tools.

The browser saving to a temp file is a bit out of scope for the main usefulness of the streaming packets api; cutting it off would defeat the main purpose of it.

**Closed by kismetwireless** 2021-01-06 14:55 UTC
